apiVersion: v1
kind: Service
metadata:
  name: devops-assignment-service
  namespace: production
  labels:
    app: devops-assignment
spec:
  type: NodePort
  selector:
    app: devops-assignment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30080
