name: Node CI/CD Pipeline

on:
  push:
    branches: ["main"]

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install

      - name: Run Tests and Save Output
        run: |
          echo "Running tests..."
          npm run check > test-results.txt || true

      - name: Upload Test Artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results.txt


  deploy:
    runs-on: self-hosted
    needs: test

    steps:
      - name: Download Test Artifact
        uses: actions/download-artifact@v4
        with:
          name: test-results

      - name: Show Test Results
        run: cat test-results.txt

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Install PM2 (if not installed)
        run: npm install -g pm2

      - name: Deploy Application
        run: |
          echo "Stopping old app if exists..."
          pm2 delete node-app || true

          echo "Starting new app..."
          pm2 start "./src/server.js" --name node-app

          echo "Saving PM2 process..."
          pm2 save
